### ISSUE TITLE
URL Redirection- Missing colon in URL

### ISSUE THREAD

**Issue by lazycipher** [dylankirby/url-shortener#2]
Hey there,

I was testing out the URL shortener deployed on `https://safe-fortress-45349.herokuapp.com/`
and encountered an error.
The short URLs are missing a colon (' : ') when redirecting and it results in server not found.

For Example - 
`https://safe-fortress-45349.herokuapp.com/3Yu `
should redirect to 
`https://github.com/krypt0r`
but instead of that it's redirecting to 
`https//github.com/krypt0r `

It's missing the colon after `https`

You should Fix this issue as the app is already deployed 👍

**Comment by dylankirby** [comment]
Thanks for the heads up. Will look into that now
